Refactor the code into multiple functions.

diff --git a/debootstrap_raspbian_chroot b/debootstrap_raspbian_chroot
--- a/debootstrap_raspbian_chroot
+++ b/debootstrap_raspbian_chroot
@@ -7,12 +7,13 @@ CHROOT=${CHROOT:-"/opt/db_raspbian"}
 # use mirrorbrain be nice to raspbian project...
 MIRROR=http://mirrordirector.raspbian.org/raspbian
 #MIRROR=http://archive.raspbian.org/raspbian
+RBINS="curl"
 XBINS="true false ls sort cp make chmod chown grep gunzip gzip mkdir mktemp rm sed seq"
-XBINS+=" debootstrap tar m4 test uniq xargs xz fold md5sum bash unzip wget curl"
+XBINS+=" debootstrap tar m4 test uniq xargs xz fold md5sum bash unzip wget"
 # binaries which arm binaries in chrooted environment
 QEMU_BINARIES="qemu-arm qemu-arm-binfmt qemu-arm-static"
 # which packages you would like to have in chroot environment by default
-INSTALL_ADDITIONAL_PACKAGES=0
+INSTALL_ADDITIONAL_PACKAGES=${INSTALL_ADDITIONAL_PACKAGES:-0}
 ADDITIONAL_PACKAGES="coreutils less sudo gawk"
 ADDITIONAL_PACKAGES+=" gcc g++ gettext libc6-dev git git-core"
 ADDITIONAL_PACKAGES+=" autoconf automake devscripts libtool make pkg-config"
@@ -64,149 +65,307 @@ function git_archive_download () {
 	fi
 }
 
-# sanity check of native host binaries
-for program in ${XBINS}; do
-	which ${program} > /dev/null 2> /dev/null
-	if [ $? -ne 0 ]; then
-		do_log "missing '${program}' on your host machine please install it" && exit -1
-	fi
-done
-
-if [ $(id -u) -ne 0 ]; then
-	do_log "Sorry must run as root" && exit -1
-fi
-
-# Sanity check that the CHROOT variable is really set
-if [ -z "${CHROOT:-}" ]; then
-	do_log "CHROOT variable must be set" && exit -1
-fi
-
-# let's make sure chroot dir is there
-if [ ! -d "${CHROOT}" ]; then
-  mkdir -p $CHROOT
-fi
-
 # Emulate correct arm CPU
 QEMU_CPU=arm1176
 LC_ALL=C
 export CHROOT XBINS QEMU_CPU LC_ALL ADDITIONAL_PACKAGES MIRROR
 
-# don't run if basic arm runtime system is not possible
-BINFMT_FOUND=0
-for fmt in  qemu-arm arm ;do
-	if [ -f /proc/sys/fs/binfmt_misc/${fmt} ];then
-		BINFMT_FOUND=$(($BINFMT_FOUND + 1))
+# ===========
+# Build steps
+# ===========
+
+# -----------------------------------------------
+# Execute all of the steps declared below
+# (i.e. all functions prefixed with "section:")
+# -----------------------------------------------
+:all() {
+	section:prepare_environment
+	section:prepare_emulation
+	section:setup_debootstrap
+	section:install_required_software
+	section:apply_additional_patches
+
+	do_log "Everything done enjoy"
+}
+
+# NOTE: See at the bottom for the :all invocation
+
+# -------------------------------------
+# Validate the run environment
+# and create the ${CHROOT} directory
+# -------------------------------------
+section:prepare_environment() {
+	__validate_host_binaries
+	__validate_is_root
+	__validate_chroot_parameter
+	__create_chroot_dir
+}
+
+__validate_host_binaries() {
+	# sanity check of native host binaries
+	for program in ${XBINS} ${RBINS}; do
+		which ${program} > /dev/null 2> /dev/null
+		if [ $? -ne 0 ]; then
+			do_log "missing '${program}' on your host machine please install it" && exit -1
+		fi
+	done
+}
+
+__validate_is_root() {
+	if [ $(id -u) -ne 0 ]; then
+		do_log "Sorry must run as root" && exit -1
 	fi
-done
-if [ $BINFMT_FOUND -lt 1 ] ; then
-	do_log "binfmt is not set please run your distribution setup procedure"
-	do_log "binfmt support must be running for this to work...." && exit -1
-fi
+}
 
-# initial preparation so arm binaries work without any issue
-mkdir -p ${CHROOT}/proc ${CHROOT}/usr/bin ${CHROOT}/usr/sbin
-NOQEMU=0
-for qemu_bin in ${QEMU_BINARIES}; do
-	if [ -x "$(which ${qemu_bin} 2>/dev/null)" ]; then
-			cp -a $(which ${qemu_bin}) ${CHROOT}/usr/bin/
-			NOQEMU=$(($NOQEMU + 1))
+__validate_chroot_parameter() {
+	# Sanity check that the CHROOT variable is really set
+	if [ -z "${CHROOT:-}" ]; then
+		do_log "CHROOT variable must be set" && exit -1
 	fi
-done
-if [ $NOQEMU -eq 0 ] ; then
-	do_log "You must have some of above mentioned binaries for this to work..." && exit -1
-fi
+}
 
-# mount proc as it is required by this process
-mount proc -t proc ${CHROOT}/proc && do_log "Mounting proc on ${CHROOT}/proc"
+__create_chroot_dir() {
+	# let's make sure chroot dir is there
+	if [ ! -d "${CHROOT}" ]; then
+	  mkdir -p "${CHROOT}"
+	fi
+}
 
-# don't run service on install
-cat > ${CHROOT}/usr/sbin/policy-rc.d << EOF
+# -----------------------------------------------
+# Prepare QEMU on the host and inside the chroot
+# to be able to execute ARM binaries
+# -----------------------------------------------
+section:prepare_emulation() {
+	__validate_binfmt
+	__validate_and_prepare_qemu
+}
+
+__validate_binfmt() {
+	# don't run if basic arm runtime system is not possible
+	BINFMT_FOUND=0
+	for fmt in  qemu-arm arm ;do
+		if [ -f /proc/sys/fs/binfmt_misc/${fmt} ];then
+			BINFMT_FOUND=$(($BINFMT_FOUND + 1))
+		fi
+	done
+	if [ ${BINFMT_FOUND} -lt 1 ] ; then
+		do_log "binfmt is not set please run your distribution setup procedure"
+		do_log "binfmt support must be running for this to work...." && exit -1
+	fi
+}
+
+__validate_and_prepare_qemu() {
+	# initial preparation so arm binaries work without any issue
+	mkdir -p "${CHROOT}/proc" "${CHROOT}/usr/bin" "${CHROOT}/usr/sbin"
+	NOQEMU=0
+	for qemu_bin in ${QEMU_BINARIES}; do
+		if [ -x "$(which ${qemu_bin} 2>/dev/null)" ]; then
+				cp -a "$(which ${qemu_bin})" "${CHROOT}/usr/bin/"
+				NOQEMU=$(($NOQEMU + 1))
+		fi
+	done
+	if [ ${NOQEMU} -eq 0 ] ; then
+		do_log "You must have some of above mentioned binaries for this to work..." && exit -1
+	fi
+}
+
+# -------------------------------------
+# Run debootstrap to create a basic OS
+# inside the chroot directory
+# -------------------------------------
+section:setup_debootstrap() {
+	__mount_proc
+	__patch_policy_rc
+	__setup_debootstrap_chroot
+}
+
+__mount_proc() {
+	# mount proc as it is required by this process
+	mount proc -t proc ${CHROOT}/proc && do_log "Mounting proc on ${CHROOT}/proc"
+}
+
+__patch_policy_rc() {
+	# don't run service on install
+	cat > ${CHROOT}/usr/sbin/policy-rc.d << EOF
 #!/bin/sh
 echo "All runlevel operations denied by policy" >&2
 exit 101
 EOF
-chmod +x ${CHROOT}/usr/sbin/policy-rc.d
 
-set -x
-debootstrap --no-check-gpg --arch=armhf --verbose wheezy ${CHROOT} ${MIRROR}
-set +x
-# Get public key...
-wget http://archive.raspbian.org/raspbian.public.key -O ${CHROOT}/tmp/raspbian.public.key
+	chmod +x ${CHROOT}/usr/sbin/policy-rc.d
+}
 
-ch_exec 'apt-key add /tmp/raspbian.public.key'
-ch_exec 'apt-get update'
-ch_exec "apt-get -y --force-yes install m4 make wget ${ADDITIONAL_PACKAGES}"
+__setup_debootstrap_chroot() {
+	do_log "Calling debootstrap to setup the chroot environment..."
+	set -x; debootstrap --no-check-gpg --arch=armhf --verbose wheezy ${CHROOT} ${MIRROR}; set +x
+}
 
-xarch=$(uname -m)
-carch=$(ch_exec 'uname -m')
+# -----------------------------------------------
+# Install all required software components into
+# the chroot, including gcc and other essentials
+# -----------------------------------------------
+section:install_required_software() {
+	subsection:install_native_packages
+	subsection:install_host_packages
+}
 
-# add ld-linux loader to all libs first
-ALL_LIBS=$(ldconfig -p|egrep '(libnss_|ld-|libnsl|libz)'|cut -d '>' -f 2)
+# -----------------------------------------------
+# Switch into the chroot and install the software
+# required by later steps, as well as all of the
+# packages specified by ALL_LIBS
+# -----------------------------------------------
+subsection:install_native_packages() {
+	__install_packages
+	__validate_chroot_creation
+}
 
-# Prepare cross compiler to be able to run it from chroot in "real" arm env
-###########(cd ${CHROOT} ; git clone https://github.com/raspberrypi/tools.git) ### way to slow....
-if [ -f /opt/master.zip ]; then
-	cp /opt/master.zip ${CHROOT}
-else
-	(cd ${CHROOT} ; git_archive_download https://github.com/raspberrypi/tools/archive/master.zip master.zip)
-fi
-#### security precaution for case that master.zip failed for some reason to be downloaded all destructive operations are done in correct place
-set -e
-(mkdir -p ${CHROOT}/etc/dpkg/dpkg.cfg.d/; echo "force-unsafe-io" > ${CHROOT}/etc/dpkg/dpkg.cfg.d/02apt-speedup)
-(mkdir -p ${CHROOT}/usr ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc/usr )
-do_log "Unpacking compiler"
-(cd ${CHROOT}; unzip master.zip)
-(cd ${CHROOT}/usr; ln -s ../tools-master/arm-bcm2708 cross)
-do_log "Fixing build root includes and libraries"
-(cd ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc/usr ; mv lib lib-orig; ln -s /usr/lib lib; mv include include-orig ; ln -s /usr/include include)
-(cd ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc ; mv lib lib-orig; ln -s /lib lib)
-do_log "Fixing compiler binaries names to be without triplets"
-(cd ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin; for i in * ; do ln -s $i $(echo $i|sed -e 's/arm-linux-gnueabihf-//g') ;done )
-ALL_LIBS=" ${ALL_LIBS} $(get_lib ld-linux.so.[2-3]) $(get_lib libstdc++.so.6) $(get_lib libz.so.1) $(get_lib libgcc_s.so.1)"
-ALL_LIBS=" ${ALL_LIBS} $(get_ldd_lib ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc) "
-set +e
-ch_exec 'uname -a'
-if [ $? -ne 0 ]; then
-	do_log "chroot not set correctly please check output of command from above" && exit -1
-fi
+__install_packages() {
+	# Get public key...
+	wget http://archive.raspbian.org/raspbian.public.key -O ${CHROOT}/tmp/raspbian.public.key
 
-do_log "Replace arm binaries with host ${xarch} alternatives"
-for executable in $XBINS ; do
-	CBIN=$(ch_exec "which ${executable}")
-	XBIN=$(which ${executable})
-	export executable CBIN XBIN
-	cp $XBIN ${CHROOT}/${CBIN}-${xarch}
-	mv ${CHROOT}/${CBIN} ${CHROOT}/${CBIN}-${carch}
-	do_log "Linking  ${executable}-${xarch} as ${executable}"
-	( cd $(dirname ${CHROOT}/${CBIN}); ln -sf ${executable}-${xarch} ${executable} )
-	ALL_LIBS="$ALL_LIBS $(get_ldd_lib $XBIN) "
-done
-do_log "Replacing dash for bash"
-(cd  ${CHROOT}/bin; ln -sf bash sh)
+	ch_exec 'apt-key add /tmp/raspbian.public.key'
+	ch_exec 'apt-get update'
+	ch_exec "apt-get -y --force-yes install m4 make wget ${ADDITIONAL_PACKAGES}"
+}
 
-do_log '"Fixing" library locations s,lib,lab,'
-for libname in $(echo $ALL_LIBS|sort|uniq) ; do
-	DNAME=${CHROOT}/$(dirname $libname|sed -e 's,lib,lab,')
-	mkdir -p ${DNAME}
-	do_log "copy host to chroot: $libname -> ${DNAME}"
-	cp  ${libname}* $DNAME
-done
-# now fix ld-linux to search into /lab /lab64 and other "labs" err libs hehe
-mkdir -p ${CHROOT}/lib64
-for libname in $(ldconfig -p|grep /ld-|cut -d '>' -f 2|sort|uniq) ; do
-	DNAME=${CHROOT}/$(dirname $libname)
-	mkdir -p ${DNAME}
-	cp  ${libname}* $DNAME
-	sed -i 's,/lib,/lab,g' ${CHROOT}${libname}*
-done
-# debian has ld-linux-x86-64.so.2 as link only in /lib64 so re-create it
-# for opensuse it will just fail with no issues
-(cd ${CHROOT}/lib64 ; ln -s /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 ld-linux-x86-64.so.2 2>/dev/null)
+__validate_chroot_creation() {
+	ch_exec 'uname -a'
+	if [ $? -ne 0 ]; then
+		do_log "chroot not set correctly please check output of command from above" && exit -1
+	fi
+}
 
-do_log "Creating initial bashrc"
-cat << EOF >> ${CHROOT}/etc/bash.bashrc
-QEMU_CPU=arm1176
-LC_ALL=C
+# ----------------------------------------------------
+# Install a number of binaries which are native
+# to the host into the chroot to achieve a better
+# performance on CPU intensive tasks (e.g. compiling)
+# ----------------------------------------------------
+subsection:install_host_packages() {
+	__determine_parameters
+	__install_rpi_tools
+	__copy_host_binaries_to_chroot
+	__fix_libraries
+}
+
+__determine_parameters() {
+	# ====================================
+	# Determine host & target architecture
+	# ====================================
+	xarch=$(uname -m)
+	carch=$(ch_exec 'uname -m')
+
+	# add ld-linux loader to all libs first
+	ALL_LIBS=$(ldconfig -p|egrep '(libnss_|ld-|libnsl|libz)'|cut -d '>' -f 2)
+}
+
+__install_rpi_tools() {
+	# ===========================================
+	# Install the RPi cross compilation toolchain
+	# ===========================================
+	# Prepare cross compiler to be able to run it from chroot in "real" arm env
+	###########(cd ${CHROOT} ; git clone https://github.com/raspberrypi/tools.git) ### way to slow....
+	if [ -f /opt/master.zip ]; then
+		cp /opt/master.zip ${CHROOT}
+	else
+		(cd ${CHROOT} ; git_archive_download https://github.com/raspberrypi/tools/archive/master.zip master.zip)
+	fi
+
+	#### security precaution for case that master.zip failed for some reason to be downloaded all destructive operations are done in correct place
+	set -e
+	(mkdir -p ${CHROOT}/etc/dpkg/dpkg.cfg.d/; echo "force-unsafe-io" > ${CHROOT}/etc/dpkg/dpkg.cfg.d/02apt-speedup)
+	(mkdir -p ${CHROOT}/usr ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc/usr )
+
+	do_log "Unpacking compiler"
+	(cd ${CHROOT}; unzip master.zip)
+	(cd ${CHROOT}/usr; ln -s ../tools-master/arm-bcm2708 cross)
+
+	do_log "Fixing build root includes and libraries"
+	(cd ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc/usr ; mv lib lib-orig; ln -s /usr/lib lib; mv include include-orig ; ln -s /usr/include include)
+	(cd ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc ; mv lib lib-orig; ln -s /lib lib)
+
+	do_log "Fixing compiler binaries names to be without triplets"
+	(cd ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin; for i in * ; do ln -s $i $(echo $i|sed -e 's/arm-linux-gnueabihf-//g') ;done )
+
+	ALL_LIBS=" ${ALL_LIBS} $(get_lib ld-linux.so.[2-3]) $(get_lib libstdc++.so.6) $(get_lib libz.so.1) $(get_lib libgcc_s.so.1)"
+	ALL_LIBS=" ${ALL_LIBS} $(get_ldd_lib ${CHROOT}/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc) "
+	set +e
+}
+
+__copy_host_binaries_to_chroot() {
+	# ========================================
+	# Copy all binaries in XBINS to the chroot
+	# ========================================
+	do_log "Replace arm binaries with host ${xarch} alternatives"
+
+	for executable in ${XBINS} ; do
+		# Determine the binaries to patch
+		CBIN=$(ch_exec "which ${executable}")
+		XBIN=$(which ${executable})
+		export executable CBIN XBIN
+
+		# Copy the host binary to the chroot,
+		# and rename the corresponding native binary
+		# so that both are suffixed with the CPU architecture
+		cp "${XBIN}"           "${CHROOT}/${CBIN}-${xarch}"
+		mv "${CHROOT}/${CBIN}" "${CHROOT}/${CBIN}-${carch}"
+
+		# Now link the default binary name to the host binary
+		do_log "Linking ${executable}-${xarch} as ${executable}"
+		( cd $(dirname ${CHROOT}/${CBIN}); ln -sf ${executable}-${xarch} ${executable} )
+
+		# Record the patched binaries in ALL_LIBS
+		ALL_LIBS+=" $(get_ldd_lib ${XBIN}) "
+	done
+
+	# =============================
+	# Special patches for the shell
+	# =============================
+	do_log "Replacing dash for bash"
+	(cd  ${CHROOT}/bin; ln -sf bash sh)
+}
+
+__fix_libraries() {
+	# =====================
+	# Fix library locations
+	# =====================
+	do_log '"Fixing" library locations s,lib,lab,'
+
+	for libname in $(echo ${ALL_LIBS}|sort|uniq) ; do
+		DNAME="${CHROOT}/$(dirname ${libname}|sed -e 's,lib,lab,')"
+		mkdir -p ${DNAME}
+		do_log "copy host to chroot: ${libname} -> ${DNAME}"
+		cp  ${libname}* ${DNAME}
+	done
+
+	# now fix ld-linux to search into /lab /lab64 and other "labs" err libs hehe
+	mkdir -p ${CHROOT}/lib64
+	for libname in $(ldconfig -p|grep /ld-|cut -d '>' -f 2|sort|uniq) ; do
+		DNAME=${CHROOT}/$(dirname $libname)
+		mkdir -p ${DNAME}
+		cp  ${libname}* $DNAME
+		sed -i 's,/lib,/lab,g' ${CHROOT}${libname}*
+	done
+
+	# debian has ld-linux-x86-64.so.2 as link only in /lib64 so re-create it
+	# for opensuse it will just fail with no issues
+	(cd ${CHROOT}/lib64 ; ln -s /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 ld-linux-x86-64.so.2 2>/dev/null)
+}
+
+# -----------------------------------------------
+# Apply additional patches to make everything
+# behave as expected inside the chroot, e.g.
+# patching the .bashrc file to set the correct
+# environment variables.
+# -----------------------------------------------
+section:apply_additional_patches() {
+	__patch_bashrc
+}
+
+__patch_bashrc() {
+	do_log "Creating initial bashrc"
+	cat << EOF >> ${CHROOT}/etc/bash.bashrc
+QEMU_CPU=${QEMU_CPU}
+LC_ALL=${LC_ALL}
 CC=arm-linux-gnueabihf-gcc
 CXX=arm-linux-gnueabihf-g++
 PATH=/usr/cross/gcc-linaro-arm-linux-gnueabihf-raspbian/bin:$PATH
@@ -218,5 +377,10 @@ alias cd..="cd .."
 alias ..="cd .."
 alias ...="cd ../.."
 EOF
+}
 
-do_log "Everything done enjoy"
+# -----------------------------------------------
+# The ':all' function is the entrypoint to
+# everything else in this bash script
+# -----------------------------------------------
+:all
